### ISSUE TITLE
ROOT.Zfs.Public.Data.PropertyValue is lacking "Name" property

### ISSUE THREAD

**Issue by ssharunas** [bjornbouetsmith/ROOT.Zfs#27]
Both, `zpool get propName` and `zfs get propName` return NAME, PROPERTY, VALUE and SOURCE columns, as mentioned in [ROOT.Zfs.Core.Helpers.PropertyValueHelper.FromString](https://github.com/bjornbouetsmith/ROOT.Zfs/blob/v1.1.6/Source/ROOT.Zfs.Core/Helpers/PropertyValueHelper.cs#L13), but currently NAME column is simply ignored by the parser.

It is troublesome to get values for the same property for all datasets. I have to do `zfs list` and then `zfs get propName dataset` for each dataset. If [ROOT.Zfs.Public.Data.PropertyValue](https://github.com/bjornbouetsmith/ROOT.Zfs/blob/v1.1.6/Source/ROOT.Zfs.Public/Data/PropertyValue.cs) would have a 'Name' property, I could get away with only one call to `zfs get propName`.

**Comment by bjornbouetsmith** [comment]
I am not 100% sure what you mean.

Can you show me a code snippet of how you are using this library?

Do you mean that you call IProperties.Get and would like that that the property value(s) returned included the dataset name as well?

**Comment by ssharunas** [comment]
> Do you mean that you call IProperties.Get and would like that that the property value(s) returned included the dataset name as well?

Yes, exactly. I would like to be able to do something like that:
```csharp
var zfs = new Zfs(connection);
var props = zfs.Properties.Get(new GetPropertyArgs() { Property = "origin", PropertyTarget = PropertyTarget.Dataset });

foreach (var prop in props)
{
	Console.WriteLine($"{prop.Name}'s origin: {prop.Value}");
}
```

**Comment by bjornbouetsmith** [comment]
Hi,
I have made change you suggested.
A 'Name' property now exists.

You can grab it from version 1.17 :-)

https://github.com/bjornbouetsmith?tab=packages&repo_name=ROOT.Zfs.

Let me know if it works for you :-)

**Comment by ssharunas** [comment]
It works great! Thank you very much!

**Comment by bjornbouetsmith** [comment]
> It works great! Thank you very much!

You are welcome :-)
